### ISSUE TITLE
Support for measuring width

### ISSUE THREAD

**Issue by gpoole** [nkbt/react-height#10]
Would you be willing to accept a PR to support width measurements as well?

**Comment by diego-toro** [comment]
👍  that could be great if @nkbt accepts, others solutions does not work well with `react-motion`

**Comment by nkbt** [comment]
Yeah, why not :) Just landed at Sydney airport, will check out soon

**Comment by gpoole** [comment]
Great, I'll tidy up and update the docs and send one over, just wanted to check first.

**Comment by nkbt** [comment]
Ah, awesome!

**Comment by nkbt** [comment]
@gpoole I'd like to ask you to keep it backward compatible and send `width` as second argument (after `height`) to `onHeightReady` callback. So it will not break any existing code.

Not a perfectly neat solution (instead of sending something like `{width, height}`), but safer for now.
