### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by s2t2** [nkbt/react-height#18]
Hi, I'm hoping you might be able to help me troubleshoot basic usage of this package (in react-native).

This is an example working component:

``` js
import React, { Component } from 'react';
import {View, Text} from 'react-native';

export default class MyComponent extends Component {
  render(){
    return (
      <View>
        <Text>Hello world</Text>
      </View>
    )
  }
}

```

This is my first attempt to use `ReactHeight`, which throws `Expected a component class, got [object Object].`: 

``` js
import React, { Component } from 'react';
import {View, Text} from 'react-native';
import ReactHeight from 'react-height';

export default class MyComponent extends Component {
  render(){
    return (
      <ReactHeight onHeightReady={height => console.log(height)}>
        <View>
          <Text>Hello world</Text>
        </View>
      </ReactHeight>
    )
  }
}
```

What am I doing wrong?

**Comment by chriswhawkins** [comment]
@s2t2, try:

```
import React, { Component } from 'react';
import { View, Text } from 'react-native';
import ReactHeight from 'react-height';

class MyComponent extends Component {
  constructor(props) {
    super(props);
    this.state = {
      height: 0,
    };
    this.onHeightReady = this.onHeightReady.bind(this);
  }

  onHeightReady(height) {
    this.setState({ height });
  }

  render() {
    return (
      <ReactHeight onHeightReady={height => console.log(height)}>
        <View>
          <Text>Hello world</Text>
        </View>
      </ReactHeight>
    );
  }
}

export default MyComponent;
```

**Comment by s2t2** [comment]
Thanks. I'll try this out, hopefully tonight, and let you know how it goes.

**Comment by s2t2** [comment]
with that exact code, i'm seeing _expected a component class, got [object Object]_

when i removed the outer `ReactHeight`, the error went away and text was rendered. this suggests the issue may be related to that component.

edit:

inspection via`react-native log-android` produced: _Warning: Failed prop type: Required prop `onHeightReady` was not specified in `ReactHeight`._

**Comment by chriswhawkins** [comment]
Oh, sorry... should be more like: `onHeightReady={this.onHeightReady}`

Here's a simplified example that's a little closer to what my actual use case was... maybe it can help: http://codepen.io/chriswhawkins/pen/gwEzdg

**Comment by s2t2** [comment]
thanks for the update. i tried implementing the named function and it produces the same error. i notice you're using normal react whereas i'm using react-native. wondering if there is a react-native compatibility issue...
