### ISSUE TITLE
How is this different from react-measure?

### ISSUE THREAD

**Issue by gmaclennan** [nkbt/react-height#2]
This seems to do the same as [react-measure](https://github.com/souporserious/react-measure) but does not use MutationObservers to check for dynamic changes in height? Just trying to figure out which library is best for me to use.

**Comment by nkbt** [comment]
Hi, @gmaclennan, I accidentally did not have this repo watched and totally missed the issue

We've been developing this solution with @souporserious pretty much the same time. It really depends on what you need.
- react-height does not support nested height change, it only checks immediate children change.
- react-height is quite simple and does not depend much on browser-specific functionality and could be used as part of react-native app with some minimal changes that I am planning to add
- `react-height` is used as backend for `react-collapse`

Besides those - not sure. I suggest to try it and decide which one works better for you.
