### ISSUE TITLE
About the height of the textarea

### ISSUE THREAD

**Issue by programmer-yang** [nkbt/react-height#32]
hello, the author

this is my code:
```
<ReactHeight onHeightReady={h => console.log(h)}>
  <textarea />
</ReactHeight>
```
When I manually change its height, defaultValue didn't respond

**Comment by nkbt** [comment]
Not sure I understand correctly what you are trying to do... what `defaultValue`? it is not in your example. What do you mean by `manually change its height`? If you mean that you change textarea height in browser - then yes, react-height will not update dynamically.

**Comment by programmer-yang** [comment]
@nkbt 
I think this problem should be is in the mechanism of the textarea
I later use `react-textarea-autosize` solved the problem
thank you
