### ISSUE TITLE
Could you create a new release ?

### ISSUE THREAD

**Issue by baptwaels** [nkbt/react-height#38]
Hi,

Could you please create a new release for this package ? 

It would solve an issue on this repositories which uses your lib:
[react-multi-select #116](https://github.com/kenshoo/react-multi-select/issues/116)

This issue was solved on this commit:
[45018e4aea524e8708ce16d4a6536759c2cbff55](https://github.com/nkbt/react-height/commit/45018e4aea524e8708ce16d4a6536759c2cbff55)

**Comment by baptwaels** [comment]
Any update @nkbt ?

**Comment by nkbt** [comment]
https://github.com/nkbt/react-height/releases/tag/v3.0.1
Published
