### ISSUE TITLE
Height not responding to width change.

### ISSUE THREAD

**Issue by thunderkid** [nkbt/react-height#5]
If you go to your codepen example, add some text, then narrow the window, the height of the text clearly changes. But this change is not reported by react-height.

**Comment by nkbt** [comment]
Window resize is actually not captured. There is some discussion around it: https://github.com/nkbt/react-collapse/issues/1

My suggestion is to wrap it in some component that listens to window resize and then enforce height recalc by setting `dirty={true}` prop.

That would be better then having it as part of react-height itself. Is it worth adding to readme?
