### ISSUE TITLE
TypeScript Types

### ISSUE THREAD

**Issue by rogerfar** [nkbt/react-height#54]
We only write TS projects nowadays but when using this library I get the error:
`Could not find a declaration file for module 'react-height'. 'index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-height` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-height';`
`

Is it possible to create a type file?

**Comment by nkbt** [comment]
Have you tried `Try npm i --save-dev @types/react-height`?

**Comment by rogerfar** [comment]
Yes, unfortunately no matches: https://www.npmjs.com/search?q=%40types%2Freact-height

**Comment by nkbt** [comment]
You can create one then in `@types` 

I am not working with TS and don't plan to anytime soon

**Comment by rogerfar** [comment]
Ok thanks I'll submit something there.
